name: Jarmynt
favicon: null
layout_spectrum: 0.8606289359740913
typography_spectrum: 0.3177356128580868
title: Jarmyn T Productions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.976561636896804
  lightness: 0.2341757440008223
  saturation: 0.19828828214667737
  rhythmicContrast: 0.1964211855083704
purpose: []
