name: Jarmynt
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3177356128580868
title: Jarmyn T Productions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101410'
    - '#1aaa33'
    - '#113217'
    - '#166d24'
    - '#17892b'
  brandStrength: 1
  lightness: 0.2341757440008223
  saturation: 0.19828828214667737
  rhythmicContrast: 0.1964211855083704
purpose: []
